// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MovieApp.Models;

namespace MovieApp.Migrations
{
    [DbContext(typeof(MovieContext))]
    partial class MovieContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.22");

            modelBuilder.Entity("MovieApp.Models.MovieResponse", b =>
                {
                    b.Property<int>("movieID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("director")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("edited")
                        .HasColumnType("INTEGER");

                    b.Property<string>("lentto")
                        .HasColumnType("TEXT");

                    b.Property<string>("notes")
                        .HasColumnType("TEXT")
                        .HasMaxLength(25);

                    b.Property<string>("rating")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("year")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("movieID");

                    b.ToTable("Responses");

                    b.HasData(
                        new
                        {
                            movieID = 1,
                            category = "Romantic Comedy",
                            director = "Mark Steven Johnson",
                            edited = false,
                            rating = "PG-13",
                            title = "When in Rome",
                            year = "2010"
                        },
                        new
                        {
                            movieID = 2,
                            category = "Comedy/Family",
                            director = "Tom McGrath",
                            edited = false,
                            rating = "PG",
                            title = "Megamind",
                            year = "2010"
                        },
                        new
                        {
                            movieID = 3,
                            category = "Action/Adventure",
                            director = "Joe Johnston",
                            edited = false,
                            rating = "PG-13",
                            title = "Captain America: The First Avenger",
                            year = "2011"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
